### ISSUE TITLE
Instance in not clear for new user

### ISSUE THREAD

**Issue by SubhashMehta** [zendesk/ios_sdk_demo_apps#26]
I have implemented build request list with jwt token. But when i have logout the user and login with new user then old user request list in showing for a sometime. After some time is updating new login user data.

Please suggest. How to resolve this issues and after logout i want to clear user data instance.

This is happing in iOS SDK swift4.2 development.

How to clear instance in iOS sdk.
let identity = Identity.createJwt(token:"Q6NijaUuMY95P7ug5u0kF")
        Zendesk.instance?.setIdentity(identity)
        let requestScreen = RequestUi.buildRequestList()
        self.navigationController?.pushViewController(requestScreen, animated: true)
![Screen Shot 2019-04-30 at 4 25 10 PM](https://user-images.githubusercontent.com/37835525/56957399-960f5680-6b64-11e9-9974-705c80497113.png)

**Comment by baz8080** [comment]
Sorry for the delay, this repo was not monitored for issues. This has been fixed since. In the future please open a ticket as described in the README
