### ISSUE TITLE
Customize `ZDCOptionView`

### ISSUE THREAD

**Issue by noorulain17** [zendesk/ios_sdk_demo_apps#29]
From the SDK and sample demo apps, it is not evident how to customize the `ZDCOptionView` in Zendesk Chat.
<img width="875" alt="Screen Shot 2019-05-29 at 4 48 35 AM" src="https://user-images.githubusercontent.com/6180345/58521317-5a9c9200-81cd-11e9-8884-d71967159f75.png">

Is there a way to customize it in the existing SDK ?

**Comment by baz8080** [comment]
There is not, sorry.
