### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by lalkrishna** [zendesk/ios_sdk_demo_apps#35]
Frameworks are not compatible with Xcode 11+. Modules should be recompiled with Swift 5.1 compiler. Required for manual installation. 

> Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Users/developer/Downloads/ios_sdk_demo_apps-master-2/SupportSDKSamples/Sample/Frameworks/ZendeskSDK.framework/Modules/ZendeskSDK.swiftmodule/arm64.swiftmodule

**Comment by bielikb** [comment]
Hi @lalkrishna,
thanks for opening this issue.
SupportSDKSamples now supports Swift 5.1/Xcode 11
