### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by EugeneGordin2303** [zendesk/ios_sdk_demo_apps#41]
Hi guys, do you have an update that fixes this issue?

**Comment by zhuravel-sergey** [comment]
I have the same problem, when will there be a fix?

**Comment by antoninnoel** [comment]
also interested in

**Comment by rgomesbr** [comment]
Also waiting for a fix…

**Comment by ganaa-enjoy** [comment]
please fix it asap

**Comment by pbpAbarsky** [comment]
Once Zendesk builds the library with the Build Libraries for Distribution checkbox checked in project settings, we'll never have to worry about this issue again.
https://forums.swift.org/t/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler/30431

**Comment by ahsaniqbalbykea** [comment]
Waiting for this fix

**Comment by rgomesbr** [comment]
> Waiting for this fix
> https://develop.zendesk.com/hc/en-us/community/posts/360031014854-Error-when-building-with-XCode-11?page=2#comments

@ahsaniqbalbykea , it has been fixed with version 3.0.3 — https://github.com/zendesk/zendesk_sdk_ios/releases/tag/3.0.3
It works for me now, with Xcode 11.2

**Comment by ahsaniqbalbykea** [comment]
Thanks! It's fixed now

**Comment by EugeneGordin2303** [comment]
Thank you
