### ISSUE TITLE
Parameters for Availability of agents

### ISSUE THREAD

**Issue by bovillaios** [zendesk/ios_sdk_demo_apps#45]
Hi Team,

Thanks for the SDK. 

I have a few questions on the Chat SDK. They are

1. Which parameter is used for determining the Availability of agents in ZDCChatAPI framework of iOS?
2. Assume, if there are 2 or more agents chatting in a conversation. How to fetch the respective agent profile image?

Please let me know if you need any inputs.

Thanks in advance,
Ram

**Comment by baz8080** [comment]
Hi Ram

1) Check here: https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/sessionapi#agent-events
2) We don't support multiple agents in the SDK yet.

If you have any followup please open a ticket as described in the README
